language: c
dist: trusty
os: linux
sudo: required
compiler: gcc
env:
    - RTE_SDK='/opt/dpdk-16.11.4' WARP17_INI_FILE='./ini/travis.ini'
cache:
  directories:
    - ./build
    - /opt/dpdk-16.11.4/*
    - $HOME/.cache/pip

before_install:
    - sudo apt install linux-headers-$(uname -r) ncurses-dev protobuf-compiler libprotobuf-dev python-protobuf libprotobuf-c0 libprotobuf-c0-dev libprotobuf8 libprotoc8 protobuf-c-compiler -y
    - sudo ./build_dpdk.sh
    - sudo pip install -r python/requirements.txt
    - sudo sysctl -w vm.nr_hugepages=1024
    - sudo mkdir -p /mnt/huge
    - sudo mount -t hugetlbfs nodev /mnt/huge
install:
    - make clean && make
script:
    - make clean && make all-kni-if
    - make clean && make all-ring-if
#    - chmod +x ./tap_interfaces.sh
#    - sudo ./tap_interfaces.sh
#    - sudo make travisut
after_script:
#    - sudo cat /tmp/warp17*/*.log
notifications:
    slack: warp17:4NA10mDvXakkJ8I4PGMOxlLg
