#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
#
# Copyright (c) 2018, Juniper Networks, Inc. All rights reserved.
#
#
# The contents of this file are subject to the terms of the BSD 3 clause
# License (the "License"). You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at
# https://github.com/Juniper/warp17/blob/master/LICENSE.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from this
# software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# File name:
#     .travis.yml
#
# Description:
#     Travis Continuous Integration config file
#
# Author:
#     Matteo Triggiani
#
# Initial Created:
#     06/22/2018
#
# Notes:
#     For now we are skipping the uts

language: c
dist: xenial
os: linux
sudo: required
compiler: gcc
env:
    - RTE_VERSION='17.11.6' RTE_SDK='/opt/dpdk-$RTE_VERSION' WARP17_INI_FILE='./ini/travis.ini'
cache:
  directories:
    - ./build
    - $RTE_SDK
    - $HOME/.cache/pip

before_install:
    - sudo ./dep_install.sh -i
    - sudo bash ./build_dpdk.sh -v $RTE_VERSION -j 2 -i
    - sudo pip install -r python/requirements.txt
    - sudo sysctl -w vm.nr_hugepages=1024
    - sudo mkdir -p /mnt/huge
    - sudo mount -t hugetlbfs nodev /mnt/huge
install:
    - make clean && make -j 2
script:
    - make clean && make all-kni-if -j 2
    - make clean && make all-ring-if -j 2
    - sudo make travis-ut
after_script:
    - sudo cat /tmp/warp17*/*.out
    - sudo cat /tmp/warp17*/*.log
after_failure:
    - sudo cat /tmp/warp17*/*.out
    - sudo cat /tmp/warp17*/*.log
notifications:
    slack: warp17:slrgF4MwJdIwf49Upb0BSIam
